---

- hosts: localhost
  # for ansible pull we use local as no SSH remote connection is needed
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name: 
          - htop
          - tmux
          - neovim
          - cmatrix
          - bat
          - fontconfig


    - name: install playbook requirements - for gnome configuration 
      become: true
      package:
        name:
          - python3-psutil
          - dconf-cli
          - dbus-tools
          - dbus-daemon

    - name: copy wallpaper file
      copy:
        src: files/ansible-wallpaper.png
        dest: /usr/share/backgrounds/ansible-wallpaper.png
        owner: root
        group: root

    - name: set wallpaper
      dconf:
        key: "/org/gome/desktop/background/picture.uri"
        value: "'file:///usr/share/backgrouds/ansible-wallpaper.png'"

    - name: set wallpaper position
      dconf:
        key: "/org/gome/desktop/background/picture-options"
        value: "'zoom'"

