---

- hosts: localhost
  # for ansible pull we use local as no SSH remote connection is needed
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name: 
          - htop
          - tmux
          - neovim
          - cmatrix


