- name: Git Checkout of Power10K for {{ ansible_user_id }}
  ansible.builtin.git:
    repo: "{{ p10k_repository_url }}"
    depth: "1"
    update: no
    version: "master"
    dest: "{{ ansible_user_id }} + / ~/powerlevel10k"


