- name: Git Checkout of Power10K for {{ p10k_users }}
  become_user: parallels
  ansible.builtin.git:
    repo: "{{ p10k_repository_url }}"
    depth: "1"
    update: no
    version: "master"
    dest: ~/powerlevel10k


